---
- name: 'Set hostname facts'
  set_fact:
    full_hostname="{{ inventory_hostname }}"
    short_hostname="{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Add bluetooth group to user'
  user:
    name: "{{ user }}"
    groups: bluetooth
    append: yes

- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/iot.git
    dest: iot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

- name: 'Install bluetooth requirements'
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - libbluetooth-dev
    - pi-bluetooth
    - bluez
    - bluez-firmware
    - libglib2.0-dev
    - libboost-python-dev
    - libboost-thread-dev
    - python-bluez

- name: 'Install python dependencies'
  pip:
    name: "{{ item }}"
    executable: pip
    state: latest
  with_items:
    - gattlib
